### ISSUE TITLE
'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by kazikfriedrich** [LukeShirnia/out-of-memory#15]
Here's the output I'm getting on Fedora 25:
```~/out-of-memory $ python -V
Python 2.7.13

~/out-of-memory $ python oom-investigate.py 
----------------------------------------
      _____ _____ _____ 
     |     |     |     |
     |  |  |  |  | | | |
     |_____|_____|_|_|_|
     Out Of Memory Analyser

Disclaimer:
If system OOMs too viciously, there may be nothing logged!
Do NOT take this script as FACT, investigate further
----------------------------------------
Unsupported OS

Error:
'NoneType' object has no attribute 'endswith'

----------------------------------------
```

**Comment by LukeShirnia** [comment]
Unsupported OS...but ill take a look at it shortly

**Comment by LukeShirnia** [comment]
Issue resolved in latest merge. 
See the following lines for resolution:
https://github.com/LukeShirnia/out-of-memory/blob/master/oom-investigate.py#L436-L448
and
https://github.com/LukeShirnia/out-of-memory/blob/master/oom-investigate.py#L549-L552
Please let me know if you are still having issues. 
Ill close this on Friday if no response.

**Comment by kazikfriedrich** [comment]
I don't have the means to test with Fedora 25 any more. Fedora 28 moved to journald and by default doesn't write anything to /var/log/messages, however I can imagine that adding support for journald systems is a major piece of work. Thanks for the fix anyway!

**Comment by LukeShirnia** [comment]
Apologies for the delay in fixing the issue. Thanks for the update. 
I have opened up https://github.com/LukeShirnia/out-of-memory/issues/17 for journalctl compatibility. 
I should be more active in issue fixes etc now.
