### ISSUE TITLE
Since python3.8 - module 'platform' has no attribute 'linux_distribution'

### ISSUE THREAD

**Issue by sumitgarg44** [LukeShirnia/out-of-memory#30]
It seems, module platform attribute linux_distribution has been deprecated since Python 3.8 because of this OOM script is failing as below. I am running python 3.12 on Ubuntu 24.04.

Traceback (most recent call last):
  File "<stdin>", line 745, in <module>
  File "<stdin>", line 737, in main
  File "<stdin>", line 632, in get_log_file
  File "<stdin>", line 75, in os_check
AttributeError: module 'platform' has no attribute 'linux_distribution'

**Comment by LukeShirnia** [comment]
Hey @sumitgarg44 thanks for raising the issue. As discussed directly, this is a problem with the old version of the script, but the newer version appears to be in working order. I'll close this issue.
